services:
  psql:
    image: postgres:13-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project_name_backend
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports: 
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - psql

volumes:
  data:
    driver: local